import argparse
import csv
import os
from collections import Counter


DEFAULT_INCLUDE = [
    "HOSS-ReID",
    "MOS-Ship",
    "OSdataset",
    "OSDataset2.0",
    "QXS-SAROPT",
]


def parse_args():
    parser = argparse.ArgumentParser(
        description="Filter audited cross-modal candidate pairs into a verified pretrain manifest."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="candidate_pairs.csv generated by audit_raw_cross_modal_datasets.py",
    )
    parser.add_argument("--output", required=True, help="Output CSV manifest path.")
    parser.add_argument(
        "--include_datasets",
        nargs="*",
        default=DEFAULT_INCLUDE,
        help="Datasets to include. 3MOS is excluded until its custom key is validated.",
    )
    parser.add_argument(
        "--check_paths",
        action="store_true",
        help="Require both source image paths to exist.",
    )
    parser.add_argument(
        "--exclude_scene_level",
        action="store_true",
        default=True,
        help="Exclude OSDataset2.0 full scene Optical.tif/sar.tif pairs.",
    )
    parser.add_argument("--max_pairs", type=int, default=0)
    return parser.parse_args()


def is_scene_level(row):
    text = " ".join(
        [
            row.get("candidate_pair_key", ""),
            row.get("opt_path", ""),
            row.get("sar_path", ""),
        ]
    ).lower()
    return "scene-level subset" in text or "scene_level subset" in text


def main():
    args = parse_args()
    include = set(args.include_datasets)
    rows = []
    rejected = Counter()
    accepted_by_dataset = Counter()

    with open(args.input, "r", encoding="utf-8-sig", newline="") as file_obj:
        reader = csv.DictReader(file_obj)
        required = {"dataset", "opt_path", "sar_path", "pair_status"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Input is missing columns: {sorted(missing)}")

        for row in reader:
            dataset = row["dataset"]
            if dataset not in include:
                rejected["dataset_not_selected"] += 1
                continue
            if row.get("pair_status") != "one_to_one":
                rejected["not_one_to_one"] += 1
                continue
            if args.exclude_scene_level and dataset == "OSDataset2.0" and is_scene_level(row):
                rejected["scene_level_excluded"] += 1
                continue
            if args.check_paths and (
                not os.path.isfile(row["opt_path"]) or not os.path.isfile(row["sar_path"])
            ):
                rejected["missing_source_path"] += 1
                continue

            row = dict(row)
            row["pair_source"] = "audited_one_to_one"
            rows.append(row)
            accepted_by_dataset[dataset] += 1
            if args.max_pairs > 0 and len(rows) >= args.max_pairs:
                break

    output_dir = os.path.dirname(os.path.abspath(args.output))
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    fieldnames = [
        "dataset",
        "candidate_pair_key",
        "opt_count",
        "sar_count",
        "opt_path",
        "sar_path",
        "pair_status",
        "pair_source",
    ]
    with open(args.output, "w", encoding="utf-8", newline="") as file_obj:
        writer = csv.DictWriter(file_obj, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print("=" * 80)
    print("VERIFIED PRETRAIN MANIFEST")
    print("=" * 80)
    print(f"Input:       {args.input}")
    print(f"Output:      {args.output}")
    print(f"Total pairs: {len(rows)}")
    print("\n[accepted by dataset]")
    for dataset, count in accepted_by_dataset.most_common():
        print(f"  {dataset:<28} {count}")
    print("\n[rejected]")
    for reason, count in rejected.most_common():
        print(f"  {reason:<28} {count}")
    if not rows:
        raise RuntimeError("No verified pretraining pairs remain after filtering.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
